# Generated by Django 2.1.7 on 2019-12-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='no answer', max_length=200, null=True)),
                ('power', models.CharField(blank=True, default='no answer', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='no answer', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BigAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(blank=True, default='no answer', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='no answer', max_length=250, null=True)),
                ('answers', models.ManyToManyField(related_name='answers', to='web.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='FirstPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_time', models.ManyToManyField(related_name='_s_free_time', to='web.Answer')),
                ('important_in_life', models.ManyToManyField(related_name='_s_important_in_life', to='web.Answer')),
                ('movie', models.ManyToManyField(related_name='_s_movie', to='web.Answer')),
                ('music', models.ManyToManyField(related_name='_s_music', to='web.Answer')),
                ('offensive_words', models.ManyToManyField(related_name='_s_offensive_words', to='web.Answer')),
                ('what_you_like', models.ManyToManyField(related_name='_s_what_you_like', to='web.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('living_place', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_place', models.CharField(blank=True, max_length=200, null=True)),
                ('martial_status', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuj', models.ManyToManyField(related_name='_s_chuj', to='web.BigAnswer')),
                ('debil', models.ManyToManyField(related_name='_s_debil', to='web.BigAnswer')),
                ('dziwka', models.ManyToManyField(related_name='_s_dziwka', to='web.BigAnswer')),
                ('idiota', models.ManyToManyField(related_name='_s_idiota', to='web.BigAnswer')),
                ('kurwa', models.ManyToManyField(related_name='_s_kurwa', to='web.BigAnswer')),
                ('pizda', models.ManyToManyField(related_name='_s_pizda', to='web.BigAnswer')),
                ('skurwysyn', models.ManyToManyField(related_name='_s_skurwysyn', to='web.BigAnswer')),
                ('szmata', models.ManyToManyField(related_name='_s_szmata', to='web.BigAnswer')),
            ],
        ),
        migrations.AddField(
            model_name='biganswer',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Responder'),
        ),
        migrations.AddField(
            model_name='answer',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Responder'),
        ),
    ]
