# Generated by Django 2.1.7 on 2019-12-11 19:52

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(blank=True, default='no answer', max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='no answer', max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='power',
            field=models.CharField(blank=True, default='no answer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responder',
            name='martial_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responder',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='chuj',
            field=models.ManyToManyField(related_name='secondpoll_chuj', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='debil',
            field=models.ManyToManyField(related_name='secondpoll_debil', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='dziwka',
            field=models.ManyToManyField(related_name='secondpoll_dziwka', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='idiota',
            field=models.ManyToManyField(related_name='secondpoll_idiota', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='kurwa',
            field=models.ManyToManyField(related_name='secondpoll_kurwa', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='pizda',
            field=models.ManyToManyField(related_name='secondpoll_pizda', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='skurwysyn',
            field=models.ManyToManyField(related_name='secondpoll_skurwysyn', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='szmata',
            field=models.ManyToManyField(related_name='secondpoll_szmata', to='web.BigAnswer'),
        ),
        migrations.AddField(
            model_name='biganswer',
            name='answers',
            field=models.ManyToManyField(related_name='biganswer_biganswer', to='web.Answer'),
        ),
        migrations.AddField(
            model_name='biganswer',
            name='responder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_responder_of', to='web.Responder'),
        ),
    ]
