# Generated by Django 2.1.7 on 2019-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191211_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='responder',
        ),
        migrations.AddField(
            model_name='answer',
            name='responder',
            field=models.ManyToManyField(related_name='answer_responder', to='web.Responder'),
        ),
        migrations.AlterField(
            model_name='biganswer',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='web.Answer'),
        ),
        migrations.RemoveField(
            model_name='biganswer',
            name='responder',
        ),
        migrations.AddField(
            model_name='biganswer',
            name='responder',
            field=models.ManyToManyField(related_name='big_answer_responder', to='web.Responder'),
        ),
        migrations.AlterField(
            model_name='firstpoll',
            name='free_time',
            field=models.ManyToManyField(related_name='_s_free_time', to='web.Answer'),
        ),
        migrations.AlterField(
            model_name='firstpoll',
            name='important_in_life',
            field=models.ManyToManyField(related_name='_s_important_in_life', to='web.Answer'),
        ),
        migrations.AlterField(
            model_name='firstpoll',
            name='movie',
            field=models.ManyToManyField(related_name='_s_movie', to='web.Answer'),
        ),
        migrations.AlterField(
            model_name='firstpoll',
            name='music',
            field=models.ManyToManyField(related_name='_s_music', to='web.Answer'),
        ),
        migrations.AlterField(
            model_name='firstpoll',
            name='offensive_words',
            field=models.ManyToManyField(related_name='_s_offensive_words', to='web.Answer'),
        ),
        migrations.AlterField(
            model_name='firstpoll',
            name='what_you_like',
            field=models.ManyToManyField(related_name='_s_what_you_like', to='web.Answer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='chuj',
            field=models.ManyToManyField(related_name='_s_chuj', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='debil',
            field=models.ManyToManyField(related_name='_s_debil', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='dziwka',
            field=models.ManyToManyField(related_name='_s_dziwka', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='idiota',
            field=models.ManyToManyField(related_name='_s_idiota', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='kurwa',
            field=models.ManyToManyField(related_name='_s_kurwa', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='pizda',
            field=models.ManyToManyField(related_name='_s_pizda', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='skurwysyn',
            field=models.ManyToManyField(related_name='_s_skurwysyn', to='web.BigAnswer'),
        ),
        migrations.AlterField(
            model_name='secondpoll',
            name='szmata',
            field=models.ManyToManyField(related_name='_s_szmata', to='web.BigAnswer'),
        ),
    ]
